---
- hosts: hypervisors
  gather_facts: yes
  vars:
    networknamager_configuration: 'initial'
  roles:
  - nfs
  - libvirt
  - networkmanager

- hosts: bastion
  gather_facts: yes
  roles:
  - openshift_installer_build
