---
- hosts: hypervisors
  gather_facts: no
  vars:
    ansible_user: root
    sudo_group: wheel
    admin_user: admin
    admin_user_uid: 901
    ssh_public_key: ~/.ssh/id_rsa.pub
  vars_prompt:
  - name: ansible_password
    prompt: "Enter Root password for remote host"

  tasks:

  - name: "Check SSH keys is present"
    local_action: stat path="{{ ssh_public_key }}"
    vars:
      ansible_become: false
    register: ssh_public_key_exists
    run_once: true

  - fail:
      msg: "Please generate SSH key pair with command: ssh-keygen -N '' -C ''"
    run_once: true
    when:
    - ssh_public_key_exists.stat.exists == False

  - include_role:
      name: add_sudo_user
