---
- hosts: hypervisors
  gather_facts: no
  vars:
    ansible_user: root
    sudo_group: wheel
    admin_user: admin
    admin_user_uid: 901
    ssh_public_key: ~/.ssh/id_rsa.pub
  vars_prompt:
  - name: remote_user_password
    prompt: "Enter Root password for remote host"
  roles:
  - add_sudo_user
