---
- hosts: hypervisors
  gather_facts: yes
  tasks:
  - include_role:
      name: libvirt
  - include_role:
      name: networkmanager
  - include_role:
      name: openshift_installer_build
    run_once: true
