---
- name: "Install GoLang support"
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - golang
  - golang-bin

- block:

  - name: "Get remote user home directoty"
    user: 
      name: "{{ ansible_user }}"
      state: present
    register: user_info

  - name: "Generate SSH keys"
    user:
      name: "{{ ansible_user}}"
      append: yes
      generate_ssh_key: yes

  - set_fact:
      source_dir: "{{ user_info.home }}/{{ openshift_installer_source_local_dir }}"

  - name: "Download OpenShift Installer Git repo"
    git:
      repo: "{{ openshift_installer_source_repo }}"
      dest: "{{ source_dir }}/src/github.com/openshift/installer"
      version: "{{ openshift_installer_source_ref }}"

  - name: "Build OpenShift installer from source"
    environment:
      TAGS: libvirt
      GOPATH: "{{ source_dir }}"
    shell: |
      src/github.com/openshift/installer/hack/build.sh
    args:
      chdir: "{{ source_dir }}"

  - debug:
      msg: "Please run manually on remote host: {{ source_dir }}/src/github.com/openshift/installer/bin/openshift-install create install-config --dir={{ user_info.home }}/{{ openshift_cluster_name }}"
#  - name: "Run OpenShift Installer to prepare config"
#    shell: |
#      {{ source_dir }}/src/github.com/openshift/installer/bin/openshift-install \
#        create install-config --dir={{ user_info.home }}/{{ openshift_cluster_name }}

  vars:
    ansible_become: false


#- name: "Remove previously built OpenShift Installer binary from localhost"
#  vars:
#    ansible_connection: local
#    ansible_become: false
#  file:
#    path: "{{ lookup('env','HOME') }}/bin/openshift-install"
#    state: absent

#- name: "Fetch just built OpenShift Installer binary to localhost"
#  fetch:
#    src: "{{ openshift_installer_source_local_dir }}/src/github.com/openshift/installer/bin/openshift-install"
#    dest: "{{ lookup('env','HOME') }}/bin/"
#    flat: yes

#- name: "Fix OpenShift Installer premissions on localhost"
#  vars:
#    ansible_connection: local
#    ansible_become: false
#  file:
#    path: "{{ lookup('env','HOME') }}/bin/openshift-install"
#    mode: 0755
