---
- include: ../../common/tasks/oc_adm.yaml

#- name: "Get remote user home directoty"
#  user:
#    name: "{{ ansible_user }}"
#    state: present
#  register: user_info
#
#- set_fact:
#    kube_config: "{{ user_info.home }}/{{ openshift_cluster_name }}/auth/kubeconfig"
#
#- set_fact:
#    oc_adm: "{{ oc_cmd }} --kubeconfig {{ kube_config }}"

- include: deploy.yaml
  when:
  - sso_deploy_action == 'deploy'

- include: undeploy.yaml
  when:
  - sso_deploy_action == 'undeploy'
