kind: Template
apiVersion: v1
metadata:
  name: nfs-client-provisioner-cluster-wide
  annotations:
    description: "An NFS Client based provisioner template (Cluster-wide Objects)"
objects:
#kind: ServiceAccount
#apiVersion: v1
#metadata:
#  name: nfs-client-provisioner
- kind: ClusterRole
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: nfs-client-provisioner-runner
  rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: run-nfs-client-provisioner
  subjects:
  - kind: ServiceAccount
    name: nfs-client-provisioner
    namespace: ${NAMESPACE}
  roleRef:
    kind: ClusterRole
    name: nfs-client-provisioner-runner
    apiGroup: rbac.authorization.k8s.io
- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: leader-locking-nfs-client-provisioner
  rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
- kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: leader-locking-nfs-client-provisioner
  subjects:
  - kind: ServiceAccount
    name: nfs-client-provisioner
    namespace: ${NAMESPACE}
  roleRef:
    kind: Role
    name: leader-locking-nfs-client-provisioner
  apiGroup: rbac.authorization.k8s.io
- apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    name: managed-nfs-storage
    annotations:
      storageclass.kubernetes.io/is-default-class: true
  provisioner: ${PROVISIONER_NAME}
  parameters:
    archiveOnDelete: "false"
parameters:
- name: NAMESPACE
  requred: true
  description: An namespaces where NFS Client based provisioner runs
- name: PROVISIONER_NAME
  value: provosioner.io/nfs-client
