---
- name: "Get remote user home directoty"
  user:
    name: "{{ ansible_user }}"
    state: present
  register: user_info

- set_fact:
    oc_adm: "{{ oc_cmd }} --kubeconfig {{ user_info.home }}/{{ openshift_cluster_name }}/auth/kubeconfig"
