---
- name: apply_sysctl
  command: sysctl -p

- name: libvirtd_service
  service:
    name: libvirtd
    state: restarted

- name: firewalld_service
  service:
    name: firewalld
    state: reloaded
